version: '3.7'
x-db-environment: &db-environment
  DB_ENGINE: django.db.backends.postgresql_psycopg2
  DB_NAME: booking
  DB_USER: postgres
  DB_PASSWORD: password123!
  DB_HOST: ec2-13-125-207-40.ap-northeast-2.compute.amazonaws.com
  HOST_ADDRESS: ec2-13-125-207-40.ap-northeast-2.compute.amazonaws.com
  DB_PORT: 5432
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=booking
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123!
    ports:
      - '5432:5432'
  web:
    build: ./Booking_Service/
    environment:
      <<: *db-environment
    command: sh -c "
        python3.9 ./manage.py migrate booking && 
        python3.9 ./manage.py runserver 0.0.0.0:8003
        "
    volumes:
      - ./Booking_Service/:/usr/src/Booking_Service
    ports:
      - '8003:8003'
  hotel:
    build: ./Hotel_Service/
    environment:
      <<: *db-environment
    command: sh -c "
        python3.9 ./manage.py migrate hotel && 
        python3.9 ./manage.py runserver 0.0.0.0:8004
        "
    volumes:
      - ./Hotel_Service/:/usr/src/Hotel_Service
    ports:
      - '8004:8004'
  session:
    build: ./Session_Service/
    environment:
      <<: *db-environment
    command: sh -c "
        python3.9 ./manage.py migrate session && 
        python3.9 ./manage.py runserver 0.0.0.0:8001
        "
    volumes:
      - ./Session_Service/:/usr/src/Session_Service
    ports:
      - '8001:8001'
  gateway:
    build: ./Gateway_Service/
    environment:
      <<: *db-environment
    command: sh -c "
        python3.9 ./manage.py migrate gateway && 
        python3.9 ./manage.py runserver 0.0.0.0:8005
        "
    volumes:
      - ./Gateway_Service/:/usr/src/Gateway_Service
    ports:
      - '8005:8005'
  loyalty:
    build: ./Loyalty_Service/
    environment:
      <<: *db-environment
    command: sh -c "
        python3.9 ./manage.py migrate loyalty && 
        python3.9 ./manage.py runserver 0.0.0.0:8000
        "
    volumes:
      - ./Loyalty_Service/:/usr/src/Loyalty_Service
    ports:
      - '8000:8000'
  payment:
    build: ./Payment_Service/
    environment:
      <<: *db-environment
    command: sh -c "
        python3.9 ./manage.py migrate payment && 
        python3.9 ./manage.py runserver 0.0.0.0:8002
        "
    volumes:
      - ./Payment_Service/:/usr/src/Payment_Service
    ports:
      - '8002:8002'
      
      
  rating:
    build: ./Rating_Service/
    environment:
      <<: *db-environment
    command: sh -c "
        python3.9 ./manage.py migrate rating && 
        python3.9 ./manage.py runserver 0.0.0.0:8007
        "
    volumes:
      - ./Rating_Service/:/usr/src/Rating_Service
    ports:
      - '8007:8007'
      
      
  report:
    build: ./Report_Service/
    environment:
      <<: *db-environment
    command: python3.9 ./manage.py runserver 0.0.0.0:8006
    volumes:
      - ./Report_Service/:/usr/src/Report_Service
    ports:
      - '8006:8006'